apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: driver
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: driver
    spec:
      containers:
      - name: driver-container
        image: "toughdaycr.azurecr.io/driver:latest"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 4567
          initialDelaySeconds: 20
          periodSeconds: 3
      imagePullSecrets:
      - name: regcred
