apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: runner
spec:
  replicas: 1
  template:
    metadata:
      labels: 
        app: runner
    spec:
      containers:
      - name: runner-container
        image: "toughdaycr.azurecr.io/runner:latest"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 4567
          initialDelaySeconds: 20
          periodSeconds: 3
      imagePullSecrets:
      - name: regcred
