apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: agent
spec:
  replicas: 2
  template:
    metadata:
      labels: 
        app: agent
    spec:
      containers:
      - name: agent-container
        image: <TD agent docker image>
        livenessProbe:
          httpGet:
            path: /health
            port: 4567
          initialDelaySeconds: 20
          periodSeconds: 3
